on:
  push:
  pull_request:
    branches:
      - devel

name: build_deploy
permissions:
  contents: write
jobs:
  build_deploy:
    runs-on: ubuntu-latest
    container: bioconductor/bioconductor_docker:devel

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Check out repo
        uses: actions/checkout@v2
        
      - name: 🛠 Install Linux system dependencies  
        run: |
          sysreqs=$(Rscript -e 'cat("apt-get update -y && apt-get install -y", paste(gsub("apt-get install -y ", "", remotes::system_requirements("ubuntu", "20.04")), collapse = " "))')
          echo $sysreqs
          sudo -s eval "$sysreqs"
          sudo apt-get install -y qpdf rsync
        shell: bash {0}

      - name: 🛠 Install latex
        uses: r-lib/actions/setup-tinytex@v2

      - name: Install dependencies
        run: |
          install.packages(c('remotes', 'BiocManager'))
          local_deps <- remotes::local_package_deps(dependencies = TRUE)
          deps <- remotes::dev_package_deps(dependencies = TRUE, repos = BiocManager::repositories())
          BiocManager::install(local_deps[local_deps %in% deps$package[deps$diff != 0]], Ncpu = 2L)
        shell: Rscript {0}

      - name: Session info
        run: |
          install.packages('sessioninfo')
          options(width = 100)
          pkgs <- installed.packages()[, "Package"]
          sessioninfo::session_info(pkgs, include_base = TRUE)
        shell: Rscript {0}

      # - name: Render book (git)
      #   run: |
      #     bookdown::render_book('index.Rmd', 'bookdown::gitbook')
      #   shell: Rscript {0}

      # - name: Render book (pdf)
      #   run: |
      #     bookdown::render_book('index.Rmd', 'bookdown::pdf_book')
      #   shell: Rscript {0}

      # - name: Render book (epub)
      #   run: |
      #     bookdown::render_book('index.Rmd', 'bookdown::epub_book')
      #   shell: Rscript {0}
        
      - name: Render book (bs4_book)
        run: |
          bookdown::render_book('index.Rmd', 'bookdown::bs4_book')
        shell: Rscript {0}
          
      - name: Deploy 🚀
        if: github.event_name == 'push' && github.ref == 'refs/heads/devel'
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: _book
